name: v7.0.0 build
run-name: CyberRT v7.0.0 build runner on ubuntu-latest ğŸš€

on:
  push:
    branches:
      - v7.0.0
    paths:
      - 'cmake/*'
      - 'cyber/*'
      - 'CMakeLists.txt'
      - 'scripts/*'

jobs:
  build-amd-ubuntu-latest:
    runs-on: ubuntu-latest # 18.04å·²ç»åœ¨2022å¹´è¢«ç§»é™¤, ç›®å‰åªæœ‰20 22 latestç‰ˆæœ¬
    steps:
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Check system info
        run: |
          uname -a
          cat /etc/*release
      - name: Install dependence
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt install -y g++ cmake libpoco-dev uuid-dev libncurses5-dev python3.9-dev
          pip3 install protobuf
          ./scripts/install.sh
      - name: Build
        run: |
          source install/setup.bash
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
