name: ubuntu20.04 v9.0.0 build arrch64
run-name: CyberRT v9.0.0 build runner on ubuntu20 arrch64 ðŸš€

on:
  push:
    paths:
      - '.github/workflows/ubuntu20-arrch64-v9.0.0-build.yaml'

  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build-arm-ubuntu20:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        env:
          DEBIAN_FRONTEND: noninteractive
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04

          install: |
            apt update
            apt install -y lsb-release git wget pkg-config g++ cmake libpoco-dev uuid-dev libncurses5-dev python3-dev

          run: |
            echo "-----------------------"
            uname -a
            lsb_release -a
            echo "-----------------------"
            bash -c "python3 install.py && source install/setup.bash && mkdir -p build && cd build && cmake .. && make -j$(nproc)"
